name: Build Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 JDK 环境（更新为 Java 17）
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # 使用 Java 17

      # 缓存 Gradle 缓存
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # 配置 Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          ndk: '23.1.7779620' # 根据需要调整版本
          cmake-version: '3.18.1' # 根据需要调整版本

      # 运行 Gradle 构建任务
      - name: Build module
        run: ./gradlew :zipRelease

      # 保存生成的 zip 文件为 GitHub Artifact
      - name: Upload module zip
        uses: actions/upload-artifact@v3
        with:
          name: Module ZIP
          path: module/release/*.zip
